import styles from "../styles/Home.module.css";
import Head from "next/head";
import Image from 'next/image'

import img1 from '../public/img/1.jpg'
import img2 from '../public/img/2.jpg'
import img3 from '../public/img/3.jpg'
import img4 from '../public/img/4.jpg'
import img5 from '../public/img/5.jpg'
import img6 from '../public/img/6.jpg'
import img7 from '../public/img/7.jpg'
import img8 from '../public/img/8.jpg'

export default function Gallery() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Gallery</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <h1 className={styles.title}>
                    This is gallery page
                    <div>
                        <div className={styles.imgContainer}>
                            <Image src={img1} width="500" height="500" layout="responsive" loading="lazy" alt="img1" className="prefetched" />
                        </div>
                        <div className={styles.imgContainer}>
                            <Image src={img2} width="500" height="500" layout="responsive" loading="lazy" alt="img2" className="prefetched" />
                        </div>
                        <div className={styles.imgContainer}>
                            <Image src={img3} width="500" height="500" layout="responsive" loading="lazy" alt="img3" className="prefetched" />
                        </div>
                        <div className={styles.imgContainer}>
                            <Image src={img4} width="500" height="500" layout="responsive" loading="lazy" alt="img4" className="prefetched" />
                        </div>
                        <div className={styles.imgContainer}>
                            <Image src={img5} width="500" height="500" layout="responsive" loading="lazy" alt="img5" className="prefetched" />
                        </div>
                        <div className={styles.imgContainer}>
                            <Image src={img6} width="500" height="500" layout="responsive" loading="lazy" alt="img6" className="prefetched" />
                        </div>
                        <div className={styles.imgContainer}>
                            <Image src={img7} width="500" height="500" layout="responsive" loading="lazy" alt="img7" className="prefetched" />
                        </div>
                        <div className={styles.imgContainer}>
                            <Image src={img8} width="500" height="500" layout="responsive" loading="lazy" alt="img8" className="prefetched" />
                        </div>
                        <div className={styles.imgContainer}>
                            <Image src={img1} width="500" height="500" layout="responsive" alt="img1" className="prefetched" />
                        </div>
                        <div className={styles.imgContainer}>
                            <Image src={img2} width="500" height="500" layout="responsive" alt="img2" className="prefetched" />
                        </div>
                    </div>
                </h1>
            </main>
        </div>
    )
}