import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { prefetch } from '@layer0/prefetch/window' // prefetch function
import { Prefetch } from '@layer0/react' // prefetch compoment
import Link from "next/link";
import {useEffect} from "react";

export default function Home() {

  useEffect(() => {
    prefetch('/page.html')
    prefetch('/about')
    prefetch('/gallery')
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Index</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <Link href="/about">
            <a className={styles.card}>
              <h2>About &rarr;</h2>
              <p>Learn more about us and our lives</p>
            </a>
          </Link>

            <Link href="/gallery">
              <a className={styles.card}>
                <h2>Gallery &rarr;</h2>
                <p>Daily updated pics from our lives</p>
              </a>
            </Link>

          <Prefetch url="/video">
            <Link href="/video">
              <a className={styles.card}>
                <h2>Video &rarr;</h2>
                <p>Watch the latest video from our lives</p>
              </a>
            </Link>
          </Prefetch>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
