import styles from "../styles/Home.module.css";
import Head from "next/head";

export default function Video() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Video</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <h1 className={styles.title}>
                    This is page with video
                </h1>
                <div>
                    <div className={styles.vidContainer}>
                        <video src="/vid/1.mp4" autoPlay loop width="640" height="480" alt="video1" className="prefetched"/>
                    </div>
                </div>
            </main>
        </div>
    )
}